version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@3.1.1
  aws-s3: circleci/aws-s3@3.0.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

  workflows:
  elastic-beanstalk-workflow:
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - aws-cli/setup
      - node/install:
          node-version: "16.14"
      - run: node --version
      - run:
          name: Front-End Install and build
          command: |
            cd udagram-frontend && npm install --legacy-peer-deps && npm run build && cd ..
      - run:
          name: Front-End Deploy
          command: |
            cd udagram-frontend && npm run deploy && cd ..
      - run:
          name: Back-End Build
          command: |
            cd udagram-api && npm install --legacy-peer-deps && npm run build && cd ..
      - eb/deploy:
        environment-name: udagram-api-dev
