version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            cd udagram-frontend && npm i && npm run build && cd..
      - run:
          name: Back-End Build
          command: |
            cd udagram-api && npm i && npm run build && cd..
