version: 2.1
orbs:
  node: circleci/node@5.0.0
  aws-cli: circleci/aws-cli@2.0.6
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - aws-cli/setup
      - eb/setup
      - node/install:
          node-version: "16.14"
      - run: node --version
      - run:
          name: Front-End and build
          command: |
            npm run Build-Frontend
      - run:
          name: Front-End Deploy
          command: |
            npm run Deploy-Frontend
      - run:
          name: Back-End Build
          command: |
            npm run Build-Backend
      - run:
          name: Back-End Deploy
          command: |
            npm run Deploy-Backend
