version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "16.14"
      - run: node --version
      - run:
          name: Front-End Install
          command: |
            cd udagram-frontend && npm install --legacy-peer-deps && npm run build && cd..
      - run:
          name: Back-End Build
          command: |
            cd udagram-api && npm i && npm run build && cd..
